name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.11.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  json_serializer: ^0.2.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_zulawy.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/